spring:
  profiles:
    include: thirdparty-mp-sdk-dev
  datasource:
    url: jdbc:mysql://192.168.1.202:3336/jlyz-test?characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: dlbroot
    password: ENC(ETWygv0bn5NoUv2V96KGbXgPbzxqxvRz)
  thymeleaf:
    prefix: classpath:/templates/
pic: 
  rootPath: C:\\upload\\picture